### ISSUE TITLE
Compat with OdinShip?

### ISSUE THREAD

**Issue by Rsslone** [blaxxun-boop/Sailing#1]
Does this apply the speed changes with the new ships added by OdinShip?

**Comment by GracefulUni** [comment]
> 

looking at the config i dont see the names and only vanilla, so i want to say no, but can go on solo world and test it by raising your skill to 100 and use a vanilla boat then an odinship

**Comment by blaxxun-boop** [comment]
The ships from OdinShip are just reskinned longships. The config option for longships will change their speeds.
But I can probably change the mod to add config options per ship name, instead of ship type.

**Comment by blaxxun-boop** [comment]
Added in v1.1.1.

**Comment by Rsslone** [comment]
I wasn't aware of how a else catch all statement was written in C#, but your code seemed to apply the long boat speed to all odin ships. But seems you already added the features so thanks for that ;p
