### ISSUE TITLE
Boat gets stuck in a speedy reverse after checking storage

### ISSUE THREAD

**Issue by Xeogin** [blaxxun-boop/Sailing#12]
This was done on a server with no mods installed, and I was a client currently riding in a boat controlled by another player who also had no mods installed.

This was the mid-tier/2nd boat and all it took the trigger it was sitting/holding fast and while doing so check the storage in the middle of the boat. The boat stopped very quickly, then quickly started going in reverse at near max speed. All of the mod settings were default.

I only have a handful of other mods installed and nothing else related to boats. Everything is the current version. I can post more details and test more later this week.

**Comment by blaxxun-boop** [comment]
We are using the mod ourselves right now and it works perfectly fine. Also, make sure that EVERYONE has all mods installed that aren't simpl UI mods. Valheim is a client-authoritative game.
