### ISSUE TITLE
Boats start driving backwards on their own

### ISSUE THREAD

**Issue by dired** [blaxxun-boop/Sailing#13]
Hello, loved the mod before the Ashlands update (made sailing bearable at all for me) but recently took it out of my list, because in multiplayer, only for one of the players the boats seem to work properly (not necessarily the host, strangely!). 

For others (seemingly randomly):

-  there is some kind of backward acceleration going on, as soon as sitting down at the rudder (speed level "0"). 
- Forward paddling isn't strong enough to overcome the backward acceleration, so it is actually feasible to drive backwards with good speed (it doesn't get faster though at a certain speed) but not as fast as driving normally.
- Only with wind from behind and at speed level 2 or 3 (sails out),  people for whom it is bugged, the boat starts to catch acceleration in the correct direction. But even in this "bugged but forward moving" mode, the boat seems slowed down by the same "wrong" backwards acceleration taking place (meaning, for the one person who can drive normally, who don't have the backward acceleration bug, they would reach a faster topspeed with sails out and wind from behind).

Since the mod hasn't been updated for 8 months, maybe the mod isn't maintained anymore, which would be understandable - your other mods are awesome and maybe more important! On the other hand there are flying mounts, bigger boats etc. for those who don't like the vanilly sailing in the first place.

Thanks a lot for your work!

**Comment by blaxxun-boop** [comment]
We are using the mod on our server without any issues whatsoever. Maybe check for other mods that interact with ships in any form.

**Comment by dired** [comment]
Alright, thanks for the fast reply, going to let you know which one
