### ISSUE TITLE
Latest Updates made the mod incompatible w/ Valheim+

### ISSUE THREAD

**Issue by Plasmid59** [blaxxun-boop/Sailing#8]
BepInEx Error:
[Error  :   BepInEx] Could not load [Sailing 1.1.6] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
That is on purpose. None of my mods work with Valheim Plus. And many other authors are doing the same. Valheim Plus is a terrible mod that hurts the modding community a lot and it shouldn't exist.

See https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.

**Comment by Plasmid59** [comment]
Oh dang, was not aware of this, and would probably explain some of the issues I've had while playing -- might take the time to find mod alternatives to the features I use w/ V+ -- thanks for the quick response!

**Comment by blaxxun-boop** [comment]
There is a list with replacements for every feature in Valheim Plus: https://github.com/AzumattDev/Valheim-Plus-Replacements

And also this mod pack as a good starting point: https://valheim.thunderstore.io/package/Azumatt/AzuQOL/
